on: [push]
name: Azure ARM
permissions:
    id-token: write
    contents: read
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: "website"
          template: ./azuredeploy.json
          scope: subscription
          parameters: ./azuredeploy.parameters.json

      
        # output containerName variable from template
      -  run: echo ${{steps.deploy.outputs.staticWebsiteUrl}}

    Upload:
      needs: build-and-deploy
      runs-on: ubuntu-latest
      steps:
        # Copy files
        - name: upload html
          uses: bacongobbler/azure-blob-storage-upload@main
          with:
            source_dir: '.'
            container_name: $web
            connection_string: ${{ secrets.CONNECTION_STRING }}
            extra_args: '--pattern *.html'
            overwrite: 'true'