on: [push]
name: Azure ARM
permissions:
    id-token: write
    contents: read
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: "website"
          template: ./azuredeploy.json
          scope: resourcegroup
          parameters: ./azuredeploy.parameters.json

        #Powershell
      - name: Enable HTTPS
        uses: azure/powershell@v1
        env:
          subId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        with:
          inlineScript: |
            
            POST https://management.azure.com/subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID}}/resourcegroups/website/providers/Microsoft.Cdn/profiles/website/endpoints/website/hodgesfamilydev/customdomains/customDomain/enableCustomHttps?api-version=2018-04-02"
          azPSVersion: "latest"


        # output containerName variable from template
      -  run: echo ${{steps.deploy.outputs.staticWebsiteUrl}}

    Upload:
      needs: build-and-deploy
      runs-on: ubuntu-latest
      steps:
        # Copy files
        - name: upload html
          uses: bacongobbler/azure-blob-storage-upload@main
          with:
            source_dir: '.'
            container_name: $web
            connection_string: ${{ secrets.CONNECTION_STRING }}
            extra_args: '--pattern *.html'
            overwrite: 'true'