name: Update Environment

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - 'MLH.Website/**'
  pull_request:
    types: [synchronize]
    paths:
      - 'MLH.Website/**'

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Get Configuration
    uses: ./.github/workflows/environment_config.yml

  update_env:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Update ${{ needs.config.outputs.type }} Environment
    runs-on: ubuntu-latest

    needs: config
    environment: ${{ needs.config.outputs.type }}

    env:
      ENVIRONMENT_NAME: ${{ needs.config.outputs.name }}
      ENVIRONMENT_TYPE: ${{ needs.config.outputs.type }}
      LCENV: ${{ needs.config.outputs.type }}

    steps:
      - uses: actions/checkout@v3

      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Get Resource Group
        shell: bash {0}
        run: |
          echo "Getting environment ${{ env.ENVIRONMENT_NAME }}..."
          environment_rg=$(az devcenter dev environment show --name ${{ env.ENVIRONMENT_NAME }} \
              --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
              --only-show-errors --query resourceGroupId --output tsv 2>&1)

          if [ $? -ne 0 ]; then
              # Prod (main) environment may not be created yet
              if [[ $environment_rg =~ "EnvironmentCannotBeFound" || $environment_rg =~ "EnvironmentNotFound" ]] && [[ "$ENVIRONMENT_TYPE" == "Prod" ]]; then
                  echo "Environment ${{ env.ENVIRONMENT_NAME }} not found, creating..."

                  environment_rg=$(az devcenter dev environment create \
                      --name ${{ env.ENVIRONMENT_NAME }} --environment-type ${{ env.ENVIRONMENT_TYPE }} \
                      --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
                      --catalog-name ${{ vars.AZURE_CATALOG }} --environment-definition-name ${{ vars.AZURE_CATALOG_ITEM }} \
                      --parameters '{ "name": "${{ env.ENVIRONMENT_NAME }}", "envName": "${{ env.ENVIRONMENT_TYPE }}" }' --only-show-errors \
                      --query resourceGroupId --output tsv 2>&1)

                  if [ $? -ne 0 ]; then
                      echo "Failed to create environment ${{ env.ENVIRONMENT_NAME }}"
                      echo "::error::az devcenter dev environment create command failed: $environment_rg"; exit 1
                  fi
              else
                  echo "Failed to get environment ${{ env.ENVIRONMENT_NAME }}"
                  echo "::error::az devcenter dev environment show command failed: $environment_rg"; exit 1
              fi
          fi

          environment_group=${environment_rg##*/}
          environment_sub=${environment_rg%/resourceGroups*}
          environment_sub=${environment_sub##*/}

          echo "ENVIRONMENT_GROUP=$environment_group" >> $GITHUB_ENV
          echo "ENVIRONMENT_SUB=$environment_sub" >> $GITHUB_ENV

          echo "- [View environment resources in the Azure portal](https://portal.azure.com/#@${{ vars.AZURE_TENANT_ID }}/resource$environment_rg)" >> $GITHUB_STEP_SUMMARY

      - name: downcase envtype
        id: inputstring
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.LCENV }}

      - name: lowercase output
        id: conv2lower
        run: |
          echo "LCENV=${{ steps.inputstring.outputs.lowercase }}" >> $GITHUB_OUTPUT

      - name: Enable Static Website
        run: |
          az storage blob service-properties update \
          --account-name ${{ format('{0}{1}{2}', 'mlhwebsite', steps.conv2lower.outputs.LCENV, 'storage') }} \
          --static-website true \
          --404-document error.html \
          --index-document index.html
  
      - name: Upload Files
        run: |
          az storage blob upload-batch \
          --account-name ${{ format('{0}{1}{2}', 'mlhwebsite', steps.conv2lower.outputs.LCENV, 'storage') }} \
          --source 'MLH.Website/HTML' \
          --destination '$web'

      - name: Enable Custom HTTPS
        run: |
          az cdn custom-domain enable-https \
          -g ${{ env.ENVIRONMENT_NAME }} \
          --profile-name ${{ format('{0}{1}{2}', 'mlhwebsite', steps.conv2lower.outputs.LCENV, 'cdnp') }} \
          --endpoint-name ${{ format('{0}{1}', 'hodgesfamily', steps.conv2lower.outputs.LCENV) }} \
          -n ${{ format('{0}.{1}', steps.conv2lower.outputs.LCENV, 'thehodgesfamily.net') }}